name: temptune
description: "A combined metronome and tone generator flutter app for musical practice, featuring preset management and custom sounds."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  circular_slider: ^0.1.1
  file_picker: ^10.3.3

  provider: ^6.1.5+1

  minisound: 
    path: /mnt/work/_projects/_dart/minisound/minisound/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/metronome/sounds/
